name = "portfolio"
main = "functions/index.js"
compatibility_date = "2023-07-01"

[[d1_databases]]
binding = "contact_db"
database_name = "contact_db"
database_id = "342a79b8-05e0-4c4d-b1f5-e108ef733468"
